SELECT CAST((
    (SELECT MAX(Lat_N) FROM (SELECT TOP 50 PERCENT Lat_N FROM Station ORDER BY Lat_N ASC) AS y) +
    (SELECT MIN(Lat_N) FROM (SELECT TOP 50 PERCENT Lat_N FROM Station ORDER BY Lat_N DESC) AS z)
) / 2 AS NUMERIC(10,4)) AS Median;
